### ISSUE TITLE
Consider a change to the makefile to support older distros?

### ISSUE THREAD

**Issue by legoman666** [jcfp/debpkg-par2tbb#1]
I had to add "-lrt" to the makefile ldadd since my distro's (Mint Maya) libc version was 2.15. According to my Google-fu libc 2.17 and up does not require this fix. Without -lrt, I get an error about an undefined reference to 'clock_gettime'.

**Comment by jcfp** [comment]
Apologies for the late reply, didn't get a notification about this.

Do you have a diff showing the exact change you made to the makefile?

**Comment by jcfp** [comment]
fixed in 8a91e92
